version: '2'
services:
  postgres:
    networks:
      default:
    image: postgres:9.6
    mem_limit: 256m
    ports:
      - "5432:5432"
  api:
    build: .
    mem_limit: 512m
    ports:
      - "3000:3000"
      - "5858:5858"
    volumes:
      - ".:/app"
networks:
  default: